apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: web-app
        image: 681863550751.dkr.ecr.us-east-1.amazonaws.com/assignment2-dev-ecr:my_app
        ports:
        - containerPort: 80  # Change this to the port your app listens on
        env:
        - name: DBHOST
          value: "mysql"  # Use the service name for the MySQL database
        - name: DBPORT
          value: "3306"  # Set this to the port your MySQL is listening on
        - name: DBUSER
          value: "root"  # Your DB user
        - name: DBPWD
          value: "pw"  # Your DB password
        - name: DATABASE
          value: "employees"  # Your database name
        - name: APP_COLOR
          value: "blue"  # Any additional config you need
