apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  imagePullSecrets:
  - name: ecr-secret
  containers:
  - name: mysql
    image: 681863550751.dkr.ecr.us-east-1.amazonaws.com/assignment2-dev-ecr:my_db
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"  # Use quotes for better compatibility
    - name: MYSQL_DATABASE
      value: "employees"  # Specify your default database name
    volumeMounts:
    - name: mysql-storage
      mountPath: /var/lib/mysql  # Path to persist MySQL data
  volumes:
  - name: mysql-storage
    emptyDir: {}  # Temporary storage; consider using a PersistentVolume in production
