apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: NodePort  # This will make the service internet-facing
  ports:
  - port: 80         # Port exposed by the service
    targetPort: 8080   # Port your application listens on in the container
    nodePort: 30000
  selector:
    app: employees     # This should match the labels in your web-app Deployment
